"""PR opener — push the generated files to a branch on the consumer repo.

v1 behavior:
  * If `FORGE_DRY_RUN=1` (or no GH credentials), log the would-be `gh` call
    and short-circuit with a structured result. Used by the doctor.
  * Else: clone the consumer repo to a temp dir, copy the generated files in,
    commit, push the branch, open a PR titled
    `chore(generated): forge sync — ontology@<sha-or-version>` with
    `--auto-merge`. Requires `GITHUB_TOKEN` + `gh` CLI on PATH.

For the doctor's local-repo path:
  * If `consumer_repo` starts with `local:`, the suffix is a path to a bare
    git repo on disk (created by the doctor). We clone, copy, commit, push to
    that bare repo. No `gh` shell-out — just `git`. The doctor then inspects
    the bare repo's refs to prove the branch landed.
"""
from __future__ import annotations

import os
import shutil
import subprocess
from datetime import datetime, timezone
from typing import Optional


def open_pr(
    *,
    consumer_repo: str,
    files_dir: str,
    source: str,
    model_version: str,
    branch: Optional[str] = None,
) -> dict:
    """Push generated files to consumer_repo on `branch`, optionally open a PR."""
    branch = branch or _default_branch(model_version)
    title = f"chore(generated): forge sync — ontology@{model_version}"
    body = (
        f"Generated by agentarmy-forge.\n\n"
        f"- source: `{source}`\n"
        f"- model.version: `{model_version}`\n"
        f"- emitted-at: `{datetime.now(timezone.utc).isoformat()}`\n\n"
        "Closes #N/A (regen). Auto-merge on green CI per ARC-ADR-029 D7."
    )

    # Local bare-repo path — for doctor + dev use. Doesn't need `gh`.
    if consumer_repo.startswith("local:"):
        bare_path = consumer_repo.removeprefix("local:")
        return _push_to_local_bare(
            bare_path=bare_path,
            files_dir=files_dir,
            branch=branch,
            title=title,
            body=body,
        )

    if os.getenv("FORGE_DRY_RUN") == "1" or not os.getenv("GITHUB_TOKEN"):
        return {
            "mode": "dry-run",
            "would_run": [
                f"gh repo clone {consumer_repo} <tmp>",
                f"git checkout -B {branch}",
                f"<copy {files_dir}/* into clone>",
                f"git commit -m {title!r}",
                f"git push -u origin {branch}",
                f"gh pr create --base main --head {branch} "
                f"--title {title!r} --body <body>",
                "gh pr merge --auto --squash",
            ],
            "consumer_repo": consumer_repo,
            "branch": branch,
        }

    return _open_pr_via_gh(
        consumer_repo=consumer_repo,
        files_dir=files_dir,
        branch=branch,
        title=title,
        body=body,
    )


def _default_branch(model_version: str) -> str:
    # Branch names can't contain `.` arbitrarily — replace for safety. The
    # version + timestamp combination is unique enough for our purposes.
    sanitized = model_version.replace(".", "-").replace("/", "-")
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    return f"forge/sync-{sanitized}-{stamp}"


def _push_to_local_bare(
    *,
    bare_path: str,
    files_dir: str,
    branch: str,
    title: str,
    body: str,
) -> dict:
    if not os.path.isdir(bare_path):
        raise FileNotFoundError(f"bare repo not found: {bare_path}")

    import tempfile

    workdir = tempfile.mkdtemp(prefix="forge-pr.")
    try:
        # Clone the bare repo. May be empty (no main branch yet) — handle both.
        _run(["git", "clone", bare_path, workdir])

        # Stage the generated files on a new branch.
        _run(["git", "-C", workdir, "checkout", "-B", branch])

        for name in sorted(os.listdir(files_dir)):
            src = os.path.join(files_dir, name)
            dst = os.path.join(workdir, name)
            if os.path.isfile(src):
                shutil.copy2(src, dst)

        _run(["git", "-C", workdir, "add", "-A"])
        # If nothing changed, exit gracefully.
        diff = subprocess.run(
            ["git", "-C", workdir, "diff", "--cached", "--quiet"],
            check=False,
        )
        if diff.returncode == 0:
            return {
                "mode": "local-bare",
                "bare": bare_path,
                "branch": branch,
                "no_change": True,
            }

        _run(
            [
                "git",
                "-C",
                workdir,
                "-c",
                "user.email=forge@agentarmy.local",
                "-c",
                "user.name=agentarmy-forge",
                "commit",
                "-m",
                title,
                "-m",
                body,
            ]
        )
        _run(["git", "-C", workdir, "push", "-u", "origin", branch])
        return {
            "mode": "local-bare",
            "bare": bare_path,
            "branch": branch,
            "title": title,
        }
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def _open_pr_via_gh(
    *,
    consumer_repo: str,
    files_dir: str,
    branch: str,
    title: str,
    body: str,
) -> dict:
    import tempfile

    workdir = tempfile.mkdtemp(prefix="forge-pr.")
    try:
        _run(["gh", "repo", "clone", consumer_repo, workdir])
        _run(["git", "-C", workdir, "checkout", "-B", branch])
        for name in sorted(os.listdir(files_dir)):
            src = os.path.join(files_dir, name)
            dst = os.path.join(workdir, name)
            if os.path.isfile(src):
                shutil.copy2(src, dst)
        _run(["git", "-C", workdir, "add", "-A"])
        diff = subprocess.run(
            ["git", "-C", workdir, "diff", "--cached", "--quiet"],
            check=False,
        )
        if diff.returncode == 0:
            return {
                "mode": "gh",
                "consumer_repo": consumer_repo,
                "branch": branch,
                "no_change": True,
            }
        _run(
            [
                "git",
                "-C",
                workdir,
                "-c",
                "user.email=forge@agentarmy.local",
                "-c",
                "user.name=agentarmy-forge",
                "commit",
                "-m",
                title,
                "-m",
                body,
            ]
        )
        _run(["git", "-C", workdir, "push", "-u", "origin", branch])
        _run(
            [
                "gh",
                "pr",
                "create",
                "--repo",
                consumer_repo,
                "--base",
                "main",
                "--head",
                branch,
                "--title",
                title,
                "--body",
                body,
            ]
        )
        _run(["gh", "pr", "merge", "--repo", consumer_repo, "--auto", "--squash", branch])
        return {
            "mode": "gh",
            "consumer_repo": consumer_repo,
            "branch": branch,
            "title": title,
            "auto_merge": True,
        }
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def _run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True)
