// <auto-generated>
//   This file was emitted by agentarmy-forge.
//   forge.version: 0.1.0
//   model.version: 1.0.0
//   source.uri:    file:///work/reference.model.yaml
//   DO NOT EDIT. Re-run forge against the source ontology to regenerate.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace AgentArmy.MiddleCore.Contracts;

/// <summary>Platform user</summary>
public record User(
    Guid Id,
    string Handle,
    DateTime CreatedAt
);

public interface IUserProjection
{
    Guid Id { get; }
    string Handle { get; }
    DateTime CreatedAt { get; }
    IReadOnlyList<IDocumentProjection> Documents { get; }
}

/// <summary>Knowledge document</summary>
public record Document(
    Guid Id,
    string Title,
    string? Body,
    int WordCount,
    DateTime CreatedAt
);

public interface IDocumentProjection
{
    Guid Id { get; }
    string Title { get; }
    string? Body { get; }
    int WordCount { get; }
    DateTime CreatedAt { get; }
    IUserProjection Author { get; }
}
