"""C# emitter — forge IR → `*.g.cs` for middle-core consumption.

Output layout:
    {out_dir}/
      DataPlatformContracts.g.cs    -- one file, all records + interfaces

Output shape (per ObjectType `Document`):
    public record Document(
        Guid Id,
        string Title,
        string? Body,
        DateTime CreatedAt
    );

    public interface IDocumentProjection
    {
        Guid Id { get; }
        string Title { get; }
        string? Body { get; }
        DateTime CreatedAt { get; }
        IUserProjection Author { get; }   // relation, cardinality=one
        // for cardinality=many: IReadOnlyList<IThingProjection> Things { get; }
    }

Why projections + records:
  * `record` is the data-carrying value type middle-core's wire format uses.
  * The `I{Name}Projection` interface is what backend-core's UDA queries
    against — it's the contract layer between storage and downstream code.

Determinism (load-bearing for the byte-identical doctor check):
  * IR iteration order is the model's declared order (parsers preserve it).
  * No timestamps in headers; only the version + source URI (which is part
    of the input, hence stable across re-runs of the same input).
  * LF line endings; one trailing LF.
"""
from __future__ import annotations

import os
from typing import Iterable

from ..ir import Field, Model, ObjectType, Relation, validate

# forge primitive -> C# type
_TYPE_MAP: dict[str, str] = {
    "string": "string",
    "int": "int",
    "long": "long",
    "float": "double",
    "bool": "bool",
    "datetime": "DateTime",
    "uuid": "Guid",
    "json": "System.Text.Json.JsonElement",
}

INDENT = "    "


def emit(model: Model, out_dir: str) -> list[str]:
    errors = validate(model)
    if errors:
        raise ValueError("invalid model: " + "; ".join(errors))

    os.makedirs(out_dir, exist_ok=True)
    contents = _render(model)
    out_path = os.path.join(out_dir, "DataPlatformContracts.g.cs")
    # Write LF endings explicitly even on Windows — the golden fixture is LF.
    with open(out_path, "wb") as f:
        f.write(contents.encode("utf-8"))
    return ["DataPlatformContracts.g.cs"]


def _render(model: Model) -> str:
    lines: list[str] = []
    lines.append("// <auto-generated>")
    lines.append("//   This file was emitted by agentarmy-forge.")
    lines.append(f"//   forge.version: {_forge_version()}")
    lines.append(f"//   model.version: {model.version}")
    lines.append(f"//   source.uri:    {model.source_uri or '<inline>'}")
    lines.append("//   DO NOT EDIT. Re-run forge against the source ontology to regenerate.")
    lines.append("// </auto-generated>")
    lines.append("#nullable enable")
    lines.append("")
    lines.append("using System;")
    lines.append("using System.Collections.Generic;")
    lines.append("")
    lines.append(f"namespace {model.namespace};")
    lines.append("")

    # IR order — parsers preserve source order (YAML mapping; explicit
    # forge:fieldOrder/relationOrder in RDF, or lex sort fallback).
    for ot in model.object_types:
        lines.extend(_render_record(ot))
        lines.append("")
        lines.extend(_render_projection(model, ot))
        lines.append("")

    # Single trailing LF.
    text = "\n".join(lines).rstrip("\n") + "\n"
    return text


def _render_record(ot: ObjectType) -> list[str]:
    out: list[str] = []
    out.append(_doc_comment(ot))
    out.append(f"public record {ot.name}(")
    params = _record_params(ot.fields)
    for i, p in enumerate(params):
        suffix = "," if i < len(params) - 1 else ""
        out.append(f"{INDENT}{p}{suffix}")
    out.append(");")
    return out


def _record_params(fields: Iterable[Field]) -> list[str]:
    params: list[str] = []
    for f in fields:
        cs_type = _cs_type(f)
        name = _pascal(f.name)
        params.append(f"{cs_type} {name}")
    return params


def _render_projection(model: Model, ot: ObjectType) -> list[str]:
    out: list[str] = []
    out.append(f"public interface I{ot.name}Projection")
    out.append("{")
    for f in ot.fields:
        cs_type = _cs_type(f)
        out.append(f"{INDENT}{cs_type} {_pascal(f.name)} {{ get; }}")
    for r in ot.relations:
        target = r.target
        if r.cardinality == "many":
            out.append(
                f"{INDENT}IReadOnlyList<I{target}Projection> {_pascal(r.name)} {{ get; }}"
            )
        else:
            out.append(f"{INDENT}I{target}Projection {_pascal(r.name)} {{ get; }}")
    out.append("}")
    return out


def _doc_comment(ot: ObjectType) -> str:
    ann = ot.annotation_map
    label = (
        ann.get("http://www.w3.org/2000/01/rdf-schema#label")
        or ann.get("rdfs:label")
        or ann.get("label")
        or ot.name
    )
    return f"/// <summary>{_xml_escape(label)}</summary>"


def _xml_escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _cs_type(f: Field) -> str:
    base = _TYPE_MAP.get(f.type, "object")
    # Value types need explicit `?` for nullable; reference types are already nullable
    # with `#nullable enable`. We just always append `?` when optional — modern Roslyn
    # accepts both `int?` and `string?` under nullable contexts.
    if f.optional:
        return f"{base}?"
    return base


def _pascal(name: str) -> str:
    """snake/camel -> PascalCase. Preserves digits."""
    out: list[str] = []
    upper_next = True
    for ch in name:
        if ch in ("_", "-"):
            upper_next = True
            continue
        if upper_next:
            out.append(ch.upper())
            upper_next = False
        else:
            out.append(ch)
    return "".join(out)


def _forge_version() -> str:
    from .. import __version__

    return __version__
