#!/usr/bin/env python3
"""Regenerate docs/spokes/index.md — the rollup of PM artifacts harvested from spoke PRs.

Driven by per-PR provenance files written by the `spoke artifact intake` workflow
(docs/spokes/<repo>/.harvest-<n>.json) plus the harvested files on disk. Idempotent:
run it any time; it rewrites only index.md. Dotfile provenance (.harvest-*.json) is
ignored by MkDocs, so it never ships to Pages.
"""

from __future__ import annotations

import json
from pathlib import Path

SPOKES_DIR = Path(__file__).resolve().parent.parent / "docs" / "spokes"
KIND_LABEL = {"spike": "Spike", "decision": "Decision", "research": "Research"}
# Files we list but don't treat as the primary readable doc.
PRIMARY_PREFERENCE = ("README.md", "readme.md", "index.md")


def load_provenance(repo_dir: Path) -> list[dict]:
    out = []
    for p in sorted(repo_dir.glob(".harvest-*.json")):
        try:
            out.append(json.loads(p.read_text(encoding="utf-8")))
        except (json.JSONDecodeError, OSError):
            continue
    # Newest PR first.
    out.sort(key=lambda d: int(d.get("number", "0") or 0), reverse=True)
    return out


def harvested_files(repo_dir: Path) -> list[Path]:
    files = [
        p
        for p in repo_dir.rglob("*")
        if p.is_file() and not p.name.startswith(".")
    ]
    return sorted(files)


def rel(p: Path) -> str:
    return p.relative_to(SPOKES_DIR).as_posix()


def build() -> str:
    lines: list[str] = []
    lines.append("# Spoke Artifacts")
    lines.append("")
    lines.append(
        "Project-management artifacts — **spikes, research notes, and ADRs** — harvested "
        "automatically from spoke pull requests by the `spoke artifact intake` pipeline. "
        "The spokes are private, so the content is copied in here (not just linked) and "
        "published to Pages. Each entry links back to the originating PR."
    )
    lines.append("")
    lines.append("> Generated by `scripts/gen_spoke_index.py` — do not edit by hand.")
    lines.append("")

    repo_dirs = sorted(d for d in SPOKES_DIR.iterdir() if d.is_dir()) if SPOKES_DIR.exists() else []
    any_content = False

    for repo_dir in repo_dirs:
        prov = load_provenance(repo_dir)
        files = harvested_files(repo_dir)
        if not prov and not files:
            continue
        any_content = True
        lines.append(f"## {repo_dir.name}")
        lines.append("")

        if prov:
            lines.append("| Kind | Artifact | PR | Author | Harvested |")
            lines.append("|---|---|---|---|---|")
            for d in prov:
                kind = KIND_LABEL.get(d.get("kind", ""), d.get("kind", "—"))
                title = (d.get("title") or "").replace("|", "\\|")
                url = d.get("url", "")
                num = d.get("number", "")
                author = d.get("author", "")
                date = d.get("date", "")
                lines.append(
                    f"| {kind} | {title} | [#{num}]({url}) | {author} | {date} |"
                )
            lines.append("")

        if files:
            lines.append("**Files:**")
            lines.append("")
            for f in files:
                lines.append(f"- [{rel(f)}]({rel(f)})")
            lines.append("")

    if not any_content:
        lines.append("_No spoke artifacts harvested yet._")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    SPOKES_DIR.mkdir(parents=True, exist_ok=True)
    (SPOKES_DIR / "index.md").write_text(build(), encoding="utf-8")
    print(f"Wrote {SPOKES_DIR / 'index.md'}")


if __name__ == "__main__":
    main()
