#!/usr/bin/env python3
"""
Generate a COMPACT subagent roster from the agent source of truth.

Why: the full agent packs (.codex/agents/*.toml, .agents/plugins/**, .claude/agents)
carry every agent's full `developer_instructions` — ~180 agents, thousands of lines.
Loading all of that as context chokes coders like Codex. This emits a lightweight
ROUTING INDEX instead: one line per agent (name + one-sentence intent), grouped by
category. A coder loads this globally, then opens only the 1-4 full definitions a task
actually needs (`.codex/agents/<name>.toml`).

Source of truth: .claude/agents/categories/<NN-category>/<name>.md frontmatter
(name + description). Category is taken from the directory, so the roster stays in
lockstep with the agents — regenerate it whenever the agent set changes.

Output: .agent/subagent-roster.md

Run:  python scripts/generate_subagent_roster.py
      (PYTHONIOENCODING=utf-8 python -X utf8 ... on Windows — descriptions may contain
       non-cp1252 glyphs.)
"""
from __future__ import annotations

import re
from pathlib import Path

# PyYAML preferred; fall back to a tiny parser so this runs in a bare env too.
try:
    import yaml  # type: ignore
except ModuleNotFoundError:
    yaml = None  # type: ignore

REPO_ROOT = Path(__file__).resolve().parents[1]
CATEGORIES_DIR = REPO_ROOT / ".claude" / "agents" / "categories"
OUT_REL = ".agent/subagent-roster.md"
SKIP_NAMES = {"README.md", "TAXONOMY.md"}


def parse_frontmatter(block: str) -> dict:
    if yaml is not None:
        data = yaml.safe_load(block)  # type: ignore[union-attr]
        return data if isinstance(data, dict) else {}
    meta: dict = {}
    key = None
    for line in block.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if m:
            key, val = m.group(1), m.group(2).strip()
            if len(val) >= 2 and val[0] in "\"'" and val[-1] == val[0]:
                val = val[1:-1]
            meta[key] = val
        elif key and line[:1] in (" ", "\t"):
            meta[key] = (str(meta.get(key, "")) + " " + line.strip()).strip()
    return meta


def one_liner(description: str, cap: int = 200) -> str:
    """First sentence of the description, whitespace-collapsed and length-capped.
    Agent descriptions often append <example> blocks — cut those off."""
    text = description.split("<example>")[0]
    text = re.sub(r"\s+", " ", text).strip()
    # Prefer cutting at the first sentence boundary if it's a reasonable length.
    m = re.search(r"(.+?[.!?])(\s|$)", text)
    if m and len(m.group(1)) <= cap:
        return m.group(1).strip()
    return (text[:cap].rstrip() + "…") if len(text) > cap else text


def collect() -> dict[str, list[tuple[str, str]]]:
    """category -> sorted [(name, one_liner)]."""
    by_cat: dict[str, list[tuple[str, str]]] = {}
    for md in sorted(CATEGORIES_DIR.rglob("*.md")):
        if md.name in SKIP_NAMES:
            continue
        content = md.read_text(encoding="utf-8")
        if not content.startswith("---"):
            continue
        parts = content.split("---", 2)
        if len(parts) < 3:
            continue
        meta = parse_frontmatter(parts[1])
        name = (meta.get("name") or "").strip()
        if not name:
            continue
        category = md.relative_to(CATEGORIES_DIR).parts[0]
        by_cat.setdefault(category, []).append((name, one_liner(meta.get("description") or "")))
    for cat in by_cat:
        by_cat[cat].sort(key=lambda t: t[0])
    return by_cat


def render(by_cat: dict[str, list[tuple[str, str]]]) -> str:
    total = sum(len(v) for v in by_cat.values())
    lines = [
        "# Subagent roster — routing index",
        "",
        "> **Generated by `scripts/generate_subagent_roster.py` — do not edit by hand.**",
        f"> {total} agents across {len(by_cat)} categories. Regenerate when the agent set changes.",
        "",
        "**How to use this (Codex / any coder):** load *this file* as the routing index — it is",
        "small on purpose. To act as a specific agent, open its full definition on demand:",
        "`.codex/agents/<name>.toml` (Codex), `.claude/agents/categories/<category>/<name>.md`",
        "(source), or `.agents/plugins/<pack>/<name>.md` (Antigravity). Do **not** load all agent",
        "definitions at once — pick the 1-4 relevant ones per task.",
        "",
    ]
    for cat in sorted(by_cat):
        pretty = cat.split("-", 1)[-1].replace("-", " ").title() if "-" in cat else cat
        lines.append(f"## {pretty}  (`{cat}`)")
        lines.append("")
        for name, desc in by_cat[cat]:
            lines.append(f"- `{name}`: {desc}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    if not CATEGORIES_DIR.is_dir():
        raise SystemExit(f"agent source not found: {CATEGORIES_DIR}")
    by_cat = collect()
    out = REPO_ROOT / OUT_REL
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(by_cat), encoding="utf-8")
    total = sum(len(v) for v in by_cat.values())
    print(f"Wrote {OUT_REL}: {total} agents across {len(by_cat)} categories.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
