from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from middle_core_model import cs_string, cs_type, load_model, pascal, validate_model


HEADER = """// <auto-generated by tools/modelgen/generate_middle_core.py />
// Generated by tools/modelgen/generate_middle_core.py. Do not edit by hand.
"""
OVERWRITABLE_ARTIFACTS = {
    "model-runtime.fixture.json",
    "model-runtime.shacl.ttl",
    "model-runtime.fixture.ttl",
}
FIXTURE_ARRAY_SIZE = 2


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate middle-core runtime contracts.")
    parser.add_argument("--model", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    model = load_model(args.model)
    errors = validate_model(model, args.model)
    if errors:
        print("middle-core model FAIL")
        for error in errors:
            print(f"ERROR {error}")
        return 1

    args.out.mkdir(parents=True, exist_ok=True)
    write_generated(args.out / "BusinessObjectTypes.g.cs", business_object_types(model))
    write_generated(args.out / "ScenarioIds.g.cs", scenario_ids(model))
    write_generated(args.out / "DataObjects.g.cs", data_objects(model))
    write_generated(args.out / "StateMachineContracts.g.cs", state_machine_contracts(model))
    write_generated(args.out / "WorkflowContracts.g.cs", workflow_contracts(model))
    write_generated(args.out / "ProjectionContracts.g.cs", projection_contracts(model))
    write_generated(args.out / "GeneratedModelValidator.g.cs", model_validator(model))
    write_generated(args.out / "ModelSummary.g.md", model_summary(model))
    write_generated(args.out / "model-runtime.fixture.json", fixture(model))
    write_generated(args.out / "model-runtime.shacl.ttl", shacl_shapes(model))
    write_generated(args.out / "model-runtime.fixture.ttl", rdf_fixture(model))
    print(f"Generated middle-core model contracts into {args.out}")
    return 0


def write_generated(path: Path, contents: str) -> None:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if ".g." not in path.name and path.name not in OVERWRITABLE_ARTIFACTS:
            raise RuntimeError(f"Refusing to overwrite non-generated file: {path}")
        if path.suffix != ".json" and "auto-generated by tools/modelgen/generate_middle_core.py" not in current:
            raise RuntimeError(f"Refusing to overwrite file without generator marker: {path}")
    path.write_text(contents, encoding="utf-8", newline="\n")


def business_object_types(model: dict[str, Any]) -> str:
    lines = [
        HEADER,
        "using System.Collections.Generic;\n",
        "namespace MiddleCore.Generated;\n",
        "public sealed record BusinessObjectContract(string Id, string DataObject, string OntologyConcept, IReadOnlyList<string> States, IReadOnlyList<string> UseCases);",
        "public static class BusinessObjectTypes",
        "{",
    ]
    for item in model["object_types"]:
        lines.append(f"    public const string {pascal(item['id'])} = {cs_string(item['id'])};")
    lines.append("}")
    lines.append("")
    lines.append("public static partial class GeneratedModel")
    lines.append("{")
    lines.append("    public static IReadOnlyList<BusinessObjectContract> BusinessObjects { get; } =")
    lines.append("    [")
    for item in model["object_types"]:
        states = ", ".join(cs_string(value) for value in item.get("states", []))
        use_cases = ", ".join(cs_string(value) for value in item.get("use_cases", []))
        lines.append(
            f"        new BusinessObjectContract(BusinessObjectTypes.{pascal(item['id'])}, {cs_string(item['data_object'])}, "
            f"{cs_string(item['ontology_concept'])}, [{states}], [{use_cases}]),"
        )
    lines.append("    ];")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def scenario_ids(model: dict[str, Any]) -> str:
    lines = [HEADER, "namespace MiddleCore.Generated;\n", "public static class ScenarioIds", "{"]
    for item in model["scenarios"]:
        lines.append(f"    public const string {pascal(item['id'])} = {cs_string(item['id'])};")
    lines.extend(["}", ""])
    return "\n".join(lines)


def data_objects(model: dict[str, Any]) -> str:
    lines = [HEADER, "using System.Collections.Generic;\n", "namespace MiddleCore.Generated;\n"]
    # data_object name -> (state_property, enum_name); binds a state field to its machine's enum.
    state_bindings = {
        ot["data_object"]: (ot["state_property"], f"{pascal(ot['id'])}State")
        for ot in model["object_types"]
        if ot.get("state_property")
    }
    for item in model["data_objects"]:
        binding = state_bindings.get(item["name"])
        parameters = []
        for prop_name, prop_type in item["properties"].items():
            cs = binding[1] if binding and prop_name == binding[0] else cs_type(prop_type)
            parameters.append(f"{cs} {pascal(prop_name)}")
        lines.append(f"public sealed record {item['name']}({', '.join(parameters)});")
    lines.append("")
    return "\n".join(lines)


def workflow_contracts(model: dict[str, Any]) -> str:
    lines = [
        HEADER,
        "using System.Collections.Generic;\n",
        "namespace MiddleCore.Generated;\n",
        "public sealed record WorkflowStepContract(string Id, string Handler, IReadOnlyList<string> Reads, IReadOnlyList<string> Writes);",
        "public static class WorkflowStepIds",
        "{",
    ]
    for item in model["workflow_steps"]:
        lines.append(f"    public const string {pascal(item['id'])} = {cs_string(item['id'])};")
    lines.append("}")
    lines.append("")
    lines.append("public static class WorkflowContracts")
    lines.append("{")
    lines.append("    public static IReadOnlyList<WorkflowStepContract> Steps { get; } =")
    lines.append("    [")
    for item in model["workflow_steps"]:
        reads = ", ".join(f"BusinessObjectTypes.{pascal(value)}" for value in item.get("reads", []))
        writes = ", ".join(f"BusinessObjectTypes.{pascal(value)}" for value in item.get("writes", []))
        lines.append(
            f"        new WorkflowStepContract({cs_string(item['id'])}, {cs_string(item['handler'])}, "
            f"[{reads}], [{writes}]),"
        )
    lines.append("    ];")
    lines.append("}")
    lines.append("")
    lines.append("public sealed record ScenarioContract(string Id, string WorkflowRef, IReadOnlyList<string> WorkflowSteps, IReadOnlyList<string> InputObjects, IReadOnlyList<string> OutputObjects);")
    lines.append("public static class ScenarioContracts")
    lines.append("{")
    lines.append("    public static IReadOnlyList<ScenarioContract> Scenarios { get; } =")
    lines.append("    [")
    for item in model["scenarios"]:
        steps = ", ".join(f"WorkflowStepIds.{pascal(value)}" for value in item.get("workflow_steps", []))
        inputs = ", ".join(f"BusinessObjectTypes.{pascal(value)}" for value in item.get("input_objects", []))
        outputs = ", ".join(f"BusinessObjectTypes.{pascal(value)}" for value in item.get("output_objects", []))
        lines.append(
            f"        new ScenarioContract({cs_string(item['id'])}, {cs_string(item['workflow_ref'])}, "
            f"[{steps}], [{inputs}], [{outputs}]),"
        )
    lines.append("    ];")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def state_machine_contracts(model: dict[str, Any]) -> str:
    lines = [
        HEADER,
        "using System.Collections.Generic;",
        "using System.Linq;\n",
        "#nullable enable\n",
        "namespace MiddleCore.Generated;\n",
        "public sealed record StateTransitionContract(string FromState, string ToState, string Trigger);",
        "public sealed record StateMachineContract(string Id, string ObjectType, string InitialState, IReadOnlyList<string> TerminalStates, IReadOnlyList<string> States, IReadOnlyList<StateTransitionContract> Transitions);",
        "public static class StateMachineIds",
        "{",
    ]
    for item in model["state_machines"]:
        lines.append(f"    public const string {pascal(item['id'])} = {cs_string(item['id'])};")
    lines.append("}")
    lines.append("")
    lines.append("public static partial class GeneratedModel")
    lines.append("{")
    lines.append("    public static IReadOnlyList<StateMachineContract> StateMachines { get; } =")
    lines.append("    [")
    for item in model["state_machines"]:
        terminal_states = ", ".join(cs_string(value) for value in item.get("terminal_states", []))
        states = ", ".join(cs_string(value) for value in item.get("states", []))
        transitions = ", ".join(
            f"new StateTransitionContract({cs_string(transition['from'])}, {cs_string(transition['to'])}, {cs_string(transition['trigger'])})"
            for transition in item.get("transitions", [])
        )
        lines.append(
            f"        new StateMachineContract(StateMachineIds.{pascal(item['id'])}, BusinessObjectTypes.{pascal(item['object_type'])}, "
            f"{cs_string(item['initial_state'])}, [{terminal_states}], [{states}], [{transitions}]),"
        )
    lines.append("    ];")
    lines.append("}")
    lines.append("")

    # One enum per machine so a typed state field cannot hold an undeclared state.
    for item in model["state_machines"]:
        lines.append(f"public enum {pascal(item['object_type'])}State")
        lines.append("{")
        for state in item.get("states", []):
            lines.append(f"    {pascal(state)},")
        lines.append("}")
        lines.append("")

    # Data-driven enforcement API the runtime can call (same invariants the
    # Python validator checks, now available at runtime).
    lines.append("public static partial class GeneratedModel")
    lines.append("{")
    lines.append("    public static StateMachineContract? StateMachineFor(string objectType) =>")
    lines.append("        StateMachines.FirstOrDefault(machine => machine.ObjectType == objectType);")
    lines.append("    public static bool IsValidState(string objectType, string state) =>")
    lines.append("        StateMachineFor(objectType)?.States.Contains(state) ?? false;")
    lines.append("    public static bool CanTransition(string objectType, string fromState, string toState) =>")
    lines.append("        StateMachineFor(objectType)?.Transitions.Any(transition => transition.FromState == fromState && transition.ToState == toState) ?? false;")
    lines.append("    public static string? InitialState(string objectType) =>")
    lines.append("        StateMachineFor(objectType)?.InitialState;")
    lines.append("    public static bool IsTerminalState(string objectType, string state) =>")
    lines.append("        StateMachineFor(objectType)?.TerminalStates.Contains(state) ?? false;")
    lines.append("}")
    lines.append("")

    # enum -> model (kebab) string. The enforcement API above is canonical on model
    # strings; the runtime holds PascalCase enums, so convert with ToModelString()
    # to avoid a casing mismatch (e.g. KnowledgeChunkState.Searchable -> "searchable").
    lines.append("public static class StateNames")
    lines.append("{")
    for item in model["state_machines"]:
        enum_name = f"{pascal(item['object_type'])}State"
        lines.append(f"    public static string ToModelString(this {enum_name} value) => value switch")
        lines.append("    {")
        for state in item.get("states", []):
            lines.append(f"        {enum_name}.{pascal(state)} => {cs_string(state)},")
        lines.append("        _ => value.ToString()")
        lines.append("    };")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def projection_contracts(model: dict[str, Any]) -> str:
    lines = [
        HEADER,
        "using System.Collections.Generic;\n",
        "namespace MiddleCore.Generated;\n",
        "public sealed record ProjectionContract(string Id, string Target, string ObjectType, string Direction, IReadOnlyList<string> ProviderRecords);",
        "public static class ProjectionContracts",
        "{",
        "    public static IReadOnlyList<ProjectionContract> Projections { get; } =",
        "    [",
    ]
    for item in model["projections"]:
        records = ", ".join(cs_string(value) for value in item.get("provider_records", []))
        lines.append(
            f"        new ProjectionContract({cs_string(item['id'])}, {cs_string(item['target'])}, "
            f"BusinessObjectTypes.{pascal(item['object_type'])}, {cs_string(item['direction'])}, [{records}]),"
        )
    lines.extend(["    ];", "}", ""])
    return "\n".join(lines)


def model_validator(model: dict[str, Any]) -> str:
    valid_objects = ", ".join(f"BusinessObjectTypes.{pascal(item['id'])}" for item in model["object_types"])
    valid_scenarios = ", ".join(f"ScenarioIds.{pascal(item['id'])}" for item in model["scenarios"])
    valid_steps = ", ".join(f"WorkflowStepIds.{pascal(item['id'])}" for item in model["workflow_steps"])
    return "\n".join(
        [
            HEADER,
            "using System.Collections.Generic;\n",
            "namespace MiddleCore.Generated;\n",
            "public sealed record GeneratedModelDescription(string ModelId, string SchemaVersion, int BusinessObjectCount, int ScenarioCount, int WorkflowStepCount, int StateMachineCount, int ProjectionCount);",
            "public static class GeneratedModelValidator",
            "{",
            f"    public const string ModelId = {cs_string(model['model_id'])};",
            f"    public const string SchemaVersion = {cs_string(model['schema_version'])};",
            f"    public static IReadOnlySet<string> ValidObjectTypes {{ get; }} = new HashSet<string>([{valid_objects}]);",
            f"    public static IReadOnlySet<string> ValidScenarios {{ get; }} = new HashSet<string>([{valid_scenarios}]);",
            f"    public static IReadOnlySet<string> ValidWorkflowSteps {{ get; }} = new HashSet<string>([{valid_steps}]);",
            "    public static bool IsObjectType(string value) => ValidObjectTypes.Contains(value);",
            "    public static bool IsScenario(string value) => ValidScenarios.Contains(value);",
            "    public static bool IsWorkflowStep(string value) => ValidWorkflowSteps.Contains(value);",
            "    public static GeneratedModelDescription Describe() => new(",
            "        ModelId,",
            "        SchemaVersion,",
            "        GeneratedModel.BusinessObjects.Count,",
            "        ScenarioContracts.Scenarios.Count,",
            "        WorkflowContracts.Steps.Count,",
            "        GeneratedModel.StateMachines.Count,",
            "        ProjectionContracts.Projections.Count);",
            "}",
            "",
        ]
    )


def model_summary(model: dict[str, Any]) -> str:
    lines = ["<!-- auto-generated by tools/modelgen/generate_middle_core.py -->", "", "# Middle-Core Generated Model Summary", ""]
    lines.append(f"- Model: `{model['model_id']}`")
    lines.append(f"- Schema: `{model['schema_version']}`")
    lines.append("")
    lines.append("## Object Types")
    lines.append("")
    lines.append("| Object | Data Object | Ontology | Use Cases |")
    lines.append("|---|---|---|---|")
    for item in model["object_types"]:
        lines.append(
            f"| `{item['id']}` | `{item['data_object']}` | `{item['ontology_concept']}` | "
            f"{', '.join(f'`{value}`' for value in item.get('use_cases', []))} |"
        )
    lines.append("")
    lines.append("## Scenarios")
    lines.append("")
    lines.append("| Scenario | Workflow | Steps |")
    lines.append("|---|---|---|")
    for item in model["scenarios"]:
        lines.append(f"| `{item['id']}` | `{item['workflow_ref']}` | {', '.join(f'`{step}`' for step in item.get('workflow_steps', []))} |")
    lines.append("")
    lines.append("## State Machines")
    lines.append("")
    lines.append("| State Machine | Object | States | Transitions |")
    lines.append("|---|---|---|---|")
    for item in model["state_machines"]:
        transitions = ", ".join(f"`{transition['from']} -> {transition['to']}`" for transition in item.get("transitions", []))
        lines.append(
            f"| `{item['id']}` | `{item['object_type']}` | "
            f"{', '.join(f'`{state}`' for state in item.get('states', []))} | {transitions} |"
        )
    return "\n".join(lines) + "\n"


def fixture(model: dict[str, Any]) -> str:
    payload = {
        "model_id": model["model_id"],
        "scenario_ids": [item["id"] for item in model["scenarios"]],
        "object_types": [item["id"] for item in model["object_types"]],
        "workflow_steps": [item["id"] for item in model["workflow_steps"]],
        "state_machines": [item["id"] for item in model["state_machines"]],
        "projections": [item["id"] for item in model["projections"]],
    }
    return json.dumps(payload, indent=2) + "\n"


def shacl_shapes(model: dict[str, Any]) -> str:
    state_machines = {item["object_type"]: item for item in model["state_machines"]}
    data_objects = {item["name"]: item["properties"] for item in model["data_objects"]}
    relationship_types = {item["id"]: item for item in model["relationship_types"]}
    lines = [
        "# auto-generated by tools/modelgen/generate_middle_core.py",
        "@prefix mc: <https://agentarmy.local/middle-core#> .",
        "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "@prefix sh: <http://www.w3.org/ns/shacl#> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        "",
    ]
    for item in model["object_types"]:
        class_name = pascal(item["id"])
        lines.extend(
            [
                f"mc:{class_name}Shape a sh:NodeShape ;",
                f"  sh:targetClass mc:{class_name} ;",
                "  sh:closed true ;",
                "  sh:ignoredProperties ( rdf:type ) ;",
            ]
        )
        for prop_name, prop_type in data_objects[item["data_object"]].items():
            lines.extend(property_shape(prop_name, prop_type, state_machines[item["id"]], item.get("state_property")))
        for rel in model["relationship_types"]:
            if rel["from"] == item["id"]:
                lines.extend(relationship_shape(rel))
        lines[-1] = lines[-1].rstrip(" ;") + " ."
        lines.append("")
    return "\n".join(lines)


def property_shape(prop_name: str, prop_type: str, state_machine: dict[str, Any], state_property: str | None) -> list[str]:
    lines = [f"  sh:property [", f"    sh:path mc:{pascal(prop_name)} ;", "    sh:minCount 1 ;"]
    if prop_type != "string[]":
        lines.append("    sh:maxCount 1 ;")
    if prop_name == state_property:
        allowed = " ".join(cs_string(state) for state in state_machine["states"])
        lines.append(f"    sh:in ( {allowed} ) ;")
    else:
        lines.append(f"    sh:datatype {xsd_type(prop_type)} ;")
    lines.append("  ] ;")
    return lines


def relationship_shape(rel: dict[str, Any]) -> list[str]:
    return [
        "  sh:property [",
        f"    sh:path mc:{pascal(rel['id'])} ;",
        "    sh:nodeKind sh:IRI ;",
        f"    sh:class mc:{pascal(rel['to'])} ;",
        "  ] ;",
    ]


def xsd_type(prop_type: str) -> str:
    return {
        "string": "xsd:string",
        "int": "xsd:integer",
        "bool": "xsd:boolean",
        "string[]": "xsd:string",
    }[prop_type]


def rdf_fixture(model: dict[str, Any]) -> str:
    state_machines = {item["object_type"]: item for item in model["state_machines"]}
    data_objects = {item["name"]: item["properties"] for item in model["data_objects"]}
    object_nodes = {item["id"]: f"mc:{pascal(item['id'])}Sample" for item in model["object_types"]}
    lines = [
        "# auto-generated by tools/modelgen/generate_middle_core.py",
        "@prefix mc: <https://agentarmy.local/middle-core#> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        "",
    ]
    for item in model["object_types"]:
        lines.append(f"{object_nodes[item['id']]} a mc:{pascal(item['id'])} ;")
        for prop_name, prop_type in data_objects[item["data_object"]].items():
            if prop_name == item.get("state_property"):
                value = ttl_literal(state_machines[item["id"]]["initial_state"], prop_type)
            else:
                value = sample_value(item["id"], prop_name, prop_type)
            lines.append(f"  mc:{pascal(prop_name)} {value} ;")
        outgoing = [rel for rel in model["relationship_types"] if rel["from"] == item["id"]]
        for rel in outgoing:
            lines.append(f"  mc:{pascal(rel['id'])} {object_nodes[rel['to']]} ;")
        lines[-1] = lines[-1].rstrip(" ;") + " ."
        lines.append("")
    return "\n".join(lines)


def sample_value(object_type: str, prop_name: str, prop_type: str) -> str:
    if prop_type == "string":
        return ttl_literal(f"{object_type}-{prop_name}", prop_type)
    if prop_type == "int":
        return ttl_literal("1", prop_type)
    if prop_type == "bool":
        return ttl_literal("true", prop_type)
    values = [ttl_literal(f"{object_type}-{prop_name}-{index}", "string") for index in range(1, FIXTURE_ARRAY_SIZE + 1)]
    return ", ".join(values)


def ttl_literal(value: str, prop_type: str) -> str:
    if prop_type == "int":
        return f'"{value}"^^xsd:integer'
    if prop_type == "bool":
        return f'"{value}"^^xsd:boolean'
    return cs_string(value)


if __name__ == "__main__":
    raise SystemExit(main())
