from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from middle_core_model import cs_string, cs_type, load_model, pascal, validate_model


HEADER = """// <auto-generated by tools/modelgen/generate_middle_core.py />
// Generated by tools/modelgen/generate_middle_core.py. Do not edit by hand.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate middle-core runtime contracts.")
    parser.add_argument("--model", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    model = load_model(args.model)
    errors = validate_model(model, args.model)
    if errors:
        print("middle-core model FAIL")
        for error in errors:
            print(f"ERROR {error}")
        return 1

    args.out.mkdir(parents=True, exist_ok=True)
    write_generated(args.out / "BusinessObjectTypes.g.cs", business_object_types(model))
    write_generated(args.out / "ScenarioIds.g.cs", scenario_ids(model))
    write_generated(args.out / "DataObjects.g.cs", data_objects(model))
    write_generated(args.out / "StateMachineContracts.g.cs", state_machine_contracts(model))
    write_generated(args.out / "WorkflowContracts.g.cs", workflow_contracts(model))
    write_generated(args.out / "ProjectionContracts.g.cs", projection_contracts(model))
    write_generated(args.out / "GeneratedModelValidator.g.cs", model_validator(model))
    write_generated(args.out / "ModelSummary.g.md", model_summary(model))
    write_generated(args.out / "model-runtime.fixture.json", fixture(model))
    print(f"Generated middle-core model contracts into {args.out}")
    return 0


def write_generated(path: Path, contents: str) -> None:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if ".g." not in path.name and not path.name.endswith(".fixture.json"):
            raise RuntimeError(f"Refusing to overwrite non-generated file: {path}")
        if path.suffix != ".json" and "auto-generated by tools/modelgen/generate_middle_core.py" not in current:
            raise RuntimeError(f"Refusing to overwrite file without generator marker: {path}")
    path.write_text(contents, encoding="utf-8", newline="\n")


def business_object_types(model: dict[str, Any]) -> str:
    lines = [
        HEADER,
        "using System.Collections.Generic;\n",
        "namespace MiddleCore.Generated;\n",
        "public sealed record BusinessObjectContract(string Id, string DataObject, string OntologyConcept, IReadOnlyList<string> States, IReadOnlyList<string> UseCases);",
        "public static class BusinessObjectTypes",
        "{",
    ]
    for item in model["object_types"]:
        lines.append(f"    public const string {pascal(item['id'])} = {cs_string(item['id'])};")
    lines.append("}")
    lines.append("")
    lines.append("public static partial class GeneratedModel")
    lines.append("{")
    lines.append("    public static IReadOnlyList<BusinessObjectContract> BusinessObjects { get; } =")
    lines.append("    [")
    for item in model["object_types"]:
        states = ", ".join(cs_string(value) for value in item.get("states", []))
        use_cases = ", ".join(cs_string(value) for value in item.get("use_cases", []))
        lines.append(
            f"        new BusinessObjectContract(BusinessObjectTypes.{pascal(item['id'])}, {cs_string(item['data_object'])}, "
            f"{cs_string(item['ontology_concept'])}, [{states}], [{use_cases}]),"
        )
    lines.append("    ];")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def scenario_ids(model: dict[str, Any]) -> str:
    lines = [HEADER, "namespace MiddleCore.Generated;\n", "public static class ScenarioIds", "{"]
    for item in model["scenarios"]:
        lines.append(f"    public const string {pascal(item['id'])} = {cs_string(item['id'])};")
    lines.extend(["}", ""])
    return "\n".join(lines)


def data_objects(model: dict[str, Any]) -> str:
    lines = [HEADER, "using System.Collections.Generic;\n", "namespace MiddleCore.Generated;\n"]
    for item in model["data_objects"]:
        parameters = []
        for prop_name, prop_type in item["properties"].items():
            parameters.append(f"{cs_type(prop_type)} {pascal(prop_name)}")
        lines.append(f"public sealed record {item['name']}({', '.join(parameters)});")
    lines.append("")
    return "\n".join(lines)


def workflow_contracts(model: dict[str, Any]) -> str:
    lines = [
        HEADER,
        "using System.Collections.Generic;\n",
        "namespace MiddleCore.Generated;\n",
        "public sealed record WorkflowStepContract(string Id, string Handler, IReadOnlyList<string> Reads, IReadOnlyList<string> Writes);",
        "public static class WorkflowStepIds",
        "{",
    ]
    for item in model["workflow_steps"]:
        lines.append(f"    public const string {pascal(item['id'])} = {cs_string(item['id'])};")
    lines.append("}")
    lines.append("")
    lines.append("public static class WorkflowContracts")
    lines.append("{")
    lines.append("    public static IReadOnlyList<WorkflowStepContract> Steps { get; } =")
    lines.append("    [")
    for item in model["workflow_steps"]:
        reads = ", ".join(f"BusinessObjectTypes.{pascal(value)}" for value in item.get("reads", []))
        writes = ", ".join(f"BusinessObjectTypes.{pascal(value)}" for value in item.get("writes", []))
        lines.append(
            f"        new WorkflowStepContract({cs_string(item['id'])}, {cs_string(item['handler'])}, "
            f"[{reads}], [{writes}]),"
        )
    lines.append("    ];")
    lines.append("}")
    lines.append("")
    lines.append("public sealed record ScenarioContract(string Id, string WorkflowRef, IReadOnlyList<string> WorkflowSteps, IReadOnlyList<string> InputObjects, IReadOnlyList<string> OutputObjects);")
    lines.append("public static class ScenarioContracts")
    lines.append("{")
    lines.append("    public static IReadOnlyList<ScenarioContract> Scenarios { get; } =")
    lines.append("    [")
    for item in model["scenarios"]:
        steps = ", ".join(f"WorkflowStepIds.{pascal(value)}" for value in item.get("workflow_steps", []))
        inputs = ", ".join(f"BusinessObjectTypes.{pascal(value)}" for value in item.get("input_objects", []))
        outputs = ", ".join(f"BusinessObjectTypes.{pascal(value)}" for value in item.get("output_objects", []))
        lines.append(
            f"        new ScenarioContract({cs_string(item['id'])}, {cs_string(item['workflow_ref'])}, "
            f"[{steps}], [{inputs}], [{outputs}]),"
        )
    lines.append("    ];")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def state_machine_contracts(model: dict[str, Any]) -> str:
    lines = [
        HEADER,
        "using System.Collections.Generic;\n",
        "namespace MiddleCore.Generated;\n",
        "public sealed record StateTransitionContract(string FromState, string ToState, string Trigger);",
        "public sealed record StateMachineContract(string Id, string ObjectType, string InitialState, IReadOnlyList<string> TerminalStates, IReadOnlyList<string> States, IReadOnlyList<StateTransitionContract> Transitions);",
        "public static class StateMachineIds",
        "{",
    ]
    for item in model["state_machines"]:
        lines.append(f"    public const string {pascal(item['id'])} = {cs_string(item['id'])};")
    lines.append("}")
    lines.append("")
    lines.append("public static partial class GeneratedModel")
    lines.append("{")
    lines.append("    public static IReadOnlyList<StateMachineContract> StateMachines { get; } =")
    lines.append("    [")
    for item in model["state_machines"]:
        terminal_states = ", ".join(cs_string(value) for value in item.get("terminal_states", []))
        states = ", ".join(cs_string(value) for value in item.get("states", []))
        transitions = ", ".join(
            f"new StateTransitionContract({cs_string(transition['from'])}, {cs_string(transition['to'])}, {cs_string(transition['trigger'])})"
            for transition in item.get("transitions", [])
        )
        lines.append(
            f"        new StateMachineContract(StateMachineIds.{pascal(item['id'])}, BusinessObjectTypes.{pascal(item['object_type'])}, "
            f"{cs_string(item['initial_state'])}, [{terminal_states}], [{states}], [{transitions}]),"
        )
    lines.append("    ];")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def projection_contracts(model: dict[str, Any]) -> str:
    lines = [
        HEADER,
        "using System.Collections.Generic;\n",
        "namespace MiddleCore.Generated;\n",
        "public sealed record ProjectionContract(string Id, string Target, string ObjectType, string Direction, IReadOnlyList<string> ProviderRecords);",
        "public static class ProjectionContracts",
        "{",
        "    public static IReadOnlyList<ProjectionContract> Projections { get; } =",
        "    [",
    ]
    for item in model["projections"]:
        records = ", ".join(cs_string(value) for value in item.get("provider_records", []))
        lines.append(
            f"        new ProjectionContract({cs_string(item['id'])}, {cs_string(item['target'])}, "
            f"BusinessObjectTypes.{pascal(item['object_type'])}, {cs_string(item['direction'])}, [{records}]),"
        )
    lines.extend(["    ];", "}", ""])
    return "\n".join(lines)


def model_validator(model: dict[str, Any]) -> str:
    valid_objects = ", ".join(f"BusinessObjectTypes.{pascal(item['id'])}" for item in model["object_types"])
    valid_scenarios = ", ".join(f"ScenarioIds.{pascal(item['id'])}" for item in model["scenarios"])
    valid_steps = ", ".join(f"WorkflowStepIds.{pascal(item['id'])}" for item in model["workflow_steps"])
    return "\n".join(
        [
            HEADER,
            "using System.Collections.Generic;\n",
            "namespace MiddleCore.Generated;\n",
            "public sealed record GeneratedModelDescription(string ModelId, string SchemaVersion, int BusinessObjectCount, int ScenarioCount, int WorkflowStepCount, int StateMachineCount, int ProjectionCount);",
            "public static class GeneratedModelValidator",
            "{",
            f"    public const string ModelId = {cs_string(model['model_id'])};",
            f"    public const string SchemaVersion = {cs_string(model['schema_version'])};",
            f"    public static IReadOnlySet<string> ValidObjectTypes {{ get; }} = new HashSet<string>([{valid_objects}]);",
            f"    public static IReadOnlySet<string> ValidScenarios {{ get; }} = new HashSet<string>([{valid_scenarios}]);",
            f"    public static IReadOnlySet<string> ValidWorkflowSteps {{ get; }} = new HashSet<string>([{valid_steps}]);",
            "    public static bool IsObjectType(string value) => ValidObjectTypes.Contains(value);",
            "    public static bool IsScenario(string value) => ValidScenarios.Contains(value);",
            "    public static bool IsWorkflowStep(string value) => ValidWorkflowSteps.Contains(value);",
            "    public static GeneratedModelDescription Describe() => new(",
            "        ModelId,",
            "        SchemaVersion,",
            "        GeneratedModel.BusinessObjects.Count,",
            "        ScenarioContracts.Scenarios.Count,",
            "        WorkflowContracts.Steps.Count,",
            "        GeneratedModel.StateMachines.Count,",
            "        ProjectionContracts.Projections.Count);",
            "}",
            "",
        ]
    )


def model_summary(model: dict[str, Any]) -> str:
    lines = ["<!-- auto-generated by tools/modelgen/generate_middle_core.py -->", "", "# Middle-Core Generated Model Summary", ""]
    lines.append(f"- Model: `{model['model_id']}`")
    lines.append(f"- Schema: `{model['schema_version']}`")
    lines.append("")
    lines.append("## Object Types")
    lines.append("")
    lines.append("| Object | Data Object | Ontology | Use Cases |")
    lines.append("|---|---|---|---|")
    for item in model["object_types"]:
        lines.append(
            f"| `{item['id']}` | `{item['data_object']}` | `{item['ontology_concept']}` | "
            f"{', '.join(f'`{value}`' for value in item.get('use_cases', []))} |"
        )
    lines.append("")
    lines.append("## Scenarios")
    lines.append("")
    lines.append("| Scenario | Workflow | Steps |")
    lines.append("|---|---|---|")
    for item in model["scenarios"]:
        lines.append(f"| `{item['id']}` | `{item['workflow_ref']}` | {', '.join(f'`{step}`' for step in item.get('workflow_steps', []))} |")
    lines.append("")
    lines.append("## State Machines")
    lines.append("")
    lines.append("| State Machine | Object | States | Transitions |")
    lines.append("|---|---|---|---|")
    for item in model["state_machines"]:
        transitions = ", ".join(f"`{transition['from']} -> {transition['to']}`" for transition in item.get("transitions", []))
        lines.append(
            f"| `{item['id']}` | `{item['object_type']}` | "
            f"{', '.join(f'`{state}`' for state in item.get('states', []))} | {transitions} |"
        )
    return "\n".join(lines) + "\n"


def fixture(model: dict[str, Any]) -> str:
    payload = {
        "model_id": model["model_id"],
        "scenario_ids": [item["id"] for item in model["scenarios"]],
        "object_types": [item["id"] for item in model["object_types"]],
        "workflow_steps": [item["id"] for item in model["workflow_steps"]],
        "state_machines": [item["id"] for item in model["state_machines"]],
        "projections": [item["id"] for item in model["projections"]],
    }
    return json.dumps(payload, indent=2) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
