#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const GLOSSARY = path.join('docs', 'glossary.md');
const args = process.argv.slice(2);
const STOP = new Set('A AN AND ARE AS AT BE BY DO FOR FROM IN IS IT OF ON OR THE TO VIA WITH YES NO'.split(' '));

function read(file) {
  try { return fs.readFileSync(file, 'utf8'); } catch { return ''; }
}

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!['includes', 'agents-glossary', 'site', '.git', 'node_modules'].includes(entry.name)) out.push(...walk(p));
    } else if (entry.name.endsWith('.md')) out.push(p);
  }
  return out;
}

function glossaryEntries() {
  const text = read(GLOSSARY);
  const entries = new Map();
  for (const m of text.matchAll(/\*\*([^*]+?)\*\*\s*—\s*([^\n]+)/g)) entries.set(m[1].trim(), m[2].trim());
  return entries;
}

if (args[0] === 'abbr') {
  const entries = glossaryEntries();
  const rows = ['<!-- GENERATED by `node tools/acronyms.mjs abbr` — do not edit by hand. Source: docs/glossary.md -->'];
  for (const [term, def] of [...entries.entries()].sort()) {
    if (/^[A-Z][A-Z0-9]{1,11}$/.test(term)) rows.push(`*[${term}]: ${def.replace(/\.$/, '')}`);
  }
  fs.mkdirSync(path.join('docs', 'includes'), { recursive: true });
  fs.writeFileSync(path.join('docs', 'includes', 'abbreviations.md'), rows.join('\n') + '\n');
  console.log(`wrote ${rows.length - 1} abbreviation(s)`);
  process.exit(0);
}

const defined = new Set([...glossaryEntries().keys()].map((k) => k.toUpperCase()));
const missing = new Map();
for (const file of walk('docs')) {
  if (file === GLOSSARY) continue;
  for (const m of read(file).matchAll(/\b[A-Z][A-Z0-9]{1,11}\b/g)) {
    const token = m[0];
    if (!STOP.has(token) && !defined.has(token)) missing.set(token, file);
  }
}

if (missing.size) {
  for (const [token, file] of [...missing.entries()].sort()) console.error(`${token}: ${file}`);
  if (args.includes('--ci')) process.exit(1);
}
console.log(missing.size ? `${missing.size} undefined acronym(s)` : 'No undefined acronyms found.');
