#!/usr/bin/env node
// tool-factory — stamp a new MCP tool (+ its Agent Skill + registry row) from the proven
// patterns, so a new capability against our abstracted APIs is "fill the spec → reconcile".
// THIN by design: it generates the repetitive 80% (a runnable FastMCP skeleton, a skill
// bundle, the registry row); the capability logic stays hand-written. Grows teeth once a
// few real tools reveal the true variation (rule of three). See feedback_serve_capabilities_via_mcp.
//
//   node tools/tool-factory.mjs new <name> [--port N] [--path /p] [--vocab V] [--auth none|bearer] [--desc "..."]
//        (dry-run preview by default — add --apply to write files + append the registry row)
//   node tools/tool-factory.mjs new board-ops --vocab workitem-fields --desc "unified board ops" --apply
//
// After --apply:  node tools/mcp-serve.mjs reconcile --apply   → live cloud+local.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REG = path.join(REPO, "tools", "mcp-registry.json");
const C = { reset: "\x1b[0m", dim: "\x1b[2m", green: "\x1b[32m", yellow: "\x1b[33m", red: "\x1b[31m", cyan: "\x1b[36m" };
const log = (s = "") => process.stdout.write(s + "\n");
const die = (s) => { log(`${C.red}✗ ${s}${C.reset}`); process.exit(1); };

function flag(name, def) { const i = process.argv.indexOf(`--${name}`); return i > -1 && process.argv[i + 1] && !process.argv[i + 1].startsWith("--") ? process.argv[i + 1] : def; }
const has = (name) => process.argv.includes(`--${name}`);

const cmd = process.argv[2];
if (cmd !== "new") die(`usage: node tools/tool-factory.mjs new <name> [--port N] [--path /p] [--vocab V] [--auth none|bearer] [--desc "..."] [--apply]`);
const name = process.argv[3];
if (!name || !/^[a-z][a-z0-9-]{1,40}$/.test(name)) die(`<name> must be kebab-case (got ${name ?? "nothing"})`);

const reg = JSON.parse(readFileSync(REG, "utf8"));
if (reg.servers.some((s) => s.name === name)) die(`'${name}' already in mcp-registry.json`);
const apply = has("apply");
const port = parseInt(flag("port", String(Math.max(8181, ...reg.servers.map((s) => s.port)) + 1)), 10);
if (reg.servers.some((s) => s.port === port)) die(`port ${port} already used in the registry`);
const route = flag("path", `/${name}`);
const vocab = flag("vocab", "api-interface");
const auth = flag("auth", "none");
const desc = flag("desc", `${name} MCP capability`);
const toolDir = path.join(REPO, "tools", `mcp-${name}`);
if (existsSync(toolDir)) die(`${path.relative(REPO, toolDir)} already exists`);
const skillDir = path.join(REPO, ".claude", "skills", name);

// ── templates ───────────────────────────────────────────────────────────
const serverPy = `"""${desc} — MCP server (generated by tool-factory). Canonical vocab: ${vocab}.

Thin skeleton: a runnable 'describe' tool plus a TODO 'run' stub. Fill the capability
logic against the CANONICAL API (the abstraction meta-service output for '${vocab}'); the
vended adapters fan it out across the real sources. Proxy backend-core for any keyed work
so secrets stay server-side (see tools/mcp-abstraction/client.py for the pattern)."""
from __future__ import annotations

import os

from mcp.server.fastmcp import FastMCP
from mcp.server.transport_security import TransportSecuritySettings

_public = os.environ.get("MCP_PUBLIC_HOST", "mcp.untool.ai")
_security = TransportSecuritySettings(
    enable_dns_rebinding_protection=True,
    allowed_hosts=[_public, "127.0.0.1:*", "localhost:*", "[::1]:*"],
    allowed_origins=[f"https://{_public}", "http://127.0.0.1:*", "http://localhost:*"],
)

mcp = FastMCP(
    "agentarmy-${name}",
    host=os.environ.get("MCP_HOST", "127.0.0.1"),
    port=int(os.environ.get("MCP_PORT", "${port}")),
    streamable_http_path=os.environ.get("MCP_PATH", "${route}"),
    transport_security=_security,
)

CANONICAL_VOCAB = "${vocab}"


@mcp.tool()
def describe() -> dict:
    """Describe this capability: its name and the canonical vocabulary it targets."""
    return {"name": "agentarmy-${name}", "vocabulary": CANONICAL_VOCAB, "status": "skeleton"}


@mcp.tool()
def run(payload: dict) -> dict:
    """TODO: implement the capability against the canonical '${vocab}' API.
    Keep keyed/engine work behind backend-core (proxy it) so secrets stay server-side."""
    raise NotImplementedError("tool-factory stub — implement run() against the canonical API")


if __name__ == "__main__":
    mcp.run(transport=os.environ.get("MCP_TRANSPORT", "stdio"))  # type: ignore[arg-type]
`;

const reqTxt = `# ${desc} MCP server (generated by tool-factory).\nmcp>=1.0\nhttpx>=0.27\n`;

const readmeMd = `# ${name} — MCP capability\n\n${desc}\n\nGenerated by \`tools/tool-factory.mjs\`. Canonical vocab: \`${vocab}\`. Served at \`${route}\` on \`:${port}\`.\n\n- Implement the capability in \`server.py\` (the \`run\` stub) against the canonical API.\n- Serve it (local + cloud) with \`node tools/mcp-serve.mjs reconcile --apply\`.\n- Cloud URL: \`https://${reg.hostname || "mcp.untool.ai"}${route}\` (behind the existing CF Access app).\n`;

const skillMd = `---
name: ${name}
description: ${desc}. Use when the task involves ${name}-style work against the canonical ${vocab} API exposed by the agentarmy-${name} MCP server.
---

# ${name}

\`agentarmy-${name}\` is an MCP server (served at \`${route}\`, locally \`127.0.0.1:${port}\`,
cloud \`https://${reg.hostname || "mcp.untool.ai"}${route}\`) exposing tools that operate
against the canonical **${vocab}** API. Reach for it when ${name} work comes up; the vended
adapters fan a single canonical call out across the real sources.

## Tools
- \`describe\` — report the capability + its canonical vocabulary.
- \`run\` — (TODO) the capability itself.

## Notes
- Keyed/engine work is proxied through backend-core, so secrets stay server-side.
`;

const row = { name, port, path: route, auth, run: "${PYTHON} tools/mcp-" + name + "/server.py", cwd: "${REPO}",
  env: { MCP_TRANSPORT: "streamable-http" }, description: desc };
if (auth === "bearer") row.tokenSecret = `${name}-mcp-key`;

// ── emit ───────────────────────────────────────────────────────────────
const files = [
  [path.join(toolDir, "server.py"), serverPy],
  [path.join(toolDir, "requirements.txt"), reqTxt],
  [path.join(toolDir, "README.md"), readmeMd],
  [path.join(skillDir, "SKILL.md"), skillMd],
];

log(`${C.cyan}tool-factory new ${name}${C.reset} ${apply ? C.yellow + "(APPLY)" + C.reset : C.dim + "(dry-run — add --apply to write)" + C.reset}`);
log(`  port=${port}  path=${route}  vocab=${vocab}  auth=${auth}`);
for (const [f] of files) log(`  ${apply ? C.green + "write" : "would write"}${C.reset} ${path.relative(REPO, f)}`);
log(`  ${apply ? C.green + "append" : "would append"}${C.reset} registry row -> tools/mcp-registry.json`);

if (!apply) {
  log(`\n${C.dim}registry row:${C.reset}`);
  log(JSON.stringify(row, null, 2));
  log(`\n${C.dim}next (after --apply): node tools/mcp-serve.mjs reconcile --apply${C.reset}`);
  process.exit(0);
}

for (const [f, content] of files) { mkdirSync(path.dirname(f), { recursive: true }); writeFileSync(f, content); }
reg.servers.push(row);
writeFileSync(REG, JSON.stringify(reg, null, 2) + "\n");
log(`\n${C.green}✓ stamped.${C.reset} Implement run() in tools/mcp-${name}/server.py, then:`);
log(`    node tools/mcp-serve.mjs reconcile --apply   ${C.dim}# ingress + persistent task + .mcp.json → live cloud+local${C.reset}`);
